<a href="https://colab.research.google.com/github/qfx4yk/ds1002-qfx4yk/blob/main/homework/week-4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 4

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

## 1. Data Types

```python
s = "Fox"
x = 17
y = "3"
z = "false"
```

Using the variables above answer these questions:

In [5]:
# Write a snippet of code that displays the data type (class) of `s`
s = "Fox"
print(s, type(s))

Fox <class 'str'>


In [36]:
# Write a snippet of code that adds `x` and `y` and displays their sum.

# Step 1: Cast the string variable y to an integer
x = 17
y = "3"
yint = int(y)

# Step 2: Now that both "x" and "yint" are integers, you can add them together
sum = x + yint
sum

20

In [35]:
# How might you transform z into a boolean value, if you had to? Be creative.

# METHOD 1

# Step 1: Create a new variable that stores the boolean value "False" DIRECTLY
z = "false"
zbool = bool(False)

# Step 2: Re-define the variable z with the newly created variable, zbool
z = zbool

# Step 3: Print the new value of z and check its "class" to make sure that it is now a boolean
print(z, type(z))

False <class 'bool'>


In [87]:
# How might you transform z into a boolean value, if you had to? Be creative.

# METHOD 2

# Step 1: Create a new variable that stores the boolean value "False" INDIRECTLY. Note that there are many arguements that could achieve this, but I chose a simpler, more direct arguement
z = "false"
zbool2 = bool(z==bool)

# Step 2: Re-define the variable z with the newly created variable, zbool
z = zbool2

# Step 3: Print the new value of z and check its "class" to make sure that it is now a boolean
print(z, type(z))

False <class 'bool'>


- - -

## 2. Lists

    mylist = ["Chicago","New Orleans", "Tempe", "Denver", "Nashville", "Albany"]

Using the list above, answer these questions:

In [34]:
mylist = ["Chicago", "New Orleans", "Tempe", "Denver", "Nashville", "Albany"]

In [33]:
# Write a snippet of code that prints out "Tempe"
print(mylist[2])

Tempe


In [50]:
# Write a snippet of code that adds "Atlanta" to this list and displays the extended list.
mylist.append("Atlanta")
print(mylist)

['Chicago', 'New Orleans', 'Tempe', 'Denver', 'Nashville', 'Albany', 'Atlanta']


In [51]:
# Write a snippet of code that prints out only "New Orleans", "Tempe", "Denver".
print(mylist[1:4])

['New Orleans', 'Tempe', 'Denver']


- - -

# 3. Dictionaries

    mydict = {"VA":"Richmond", "NC":"Raleigh", "NJ":"Trenton", "PA":"Harrisburg", "NY":"Albany"}

Answer the following questions:

In [53]:
mydict = {"VA":"Richmond", "NC":"Raleigh", "NJ":"Trenton", "PA":"Harrisburg", "NY":"Albany"}

In [59]:
# Write a snippet of code that returns "Trenton".
print(mydict["NJ"])

Trenton


In [60]:
# Write a snippet of code that adds "CO":"Denver" to `mydict`.
# Remember the built-in .update({'key': 'value'}) method.
mydict.update({"CO":"Denver"})
mydict

{'VA': 'Richmond',
 'NC': 'Raleigh',
 'NJ': 'Trenton',
 'PA': 'Harrisburg',
 'NY': 'Albany',
 'CO': 'Denver'}

In [63]:
# Write a snippet of code that returns all the keys in `mydict`
mydict.keys()

dict_keys(['VA', 'NC', 'NJ', 'PA', 'NY', 'CO'])

- - -

# 4. NumPy Arrays

Create an `ndarray` that contains the following values and assign the array to a variable.

    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37

Using that variable, answer the following questions:

In [64]:
import numpy as np

In [65]:
alist = [2,3,5,7,11,13,17,19,23,29,31,37]
y = np.array(alist)
y

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37])

In [88]:
# Write a snippet of code that prints the data type of the elements in the array.

# PART 1 -
# Printing the data type of EACH value in the array
# The output tells us that each value is part of a numpy array and is an integer

for value in y:
  print("Value:",value)
  print("Data Type:",type(value))
  print(' ')

Value: 2
Data Type: <class 'numpy.int64'>
 
Value: 3
Data Type: <class 'numpy.int64'>
 
Value: 5
Data Type: <class 'numpy.int64'>
 
Value: 7
Data Type: <class 'numpy.int64'>
 
Value: 11
Data Type: <class 'numpy.int64'>
 
Value: 13
Data Type: <class 'numpy.int64'>
 
Value: 17
Data Type: <class 'numpy.int64'>
 
Value: 19
Data Type: <class 'numpy.int64'>
 
Value: 23
Data Type: <class 'numpy.int64'>
 
Value: 29
Data Type: <class 'numpy.int64'>
 
Value: 31
Data Type: <class 'numpy.int64'>
 
Value: 37
Data Type: <class 'numpy.int64'>
 


In [89]:
# Write a snippet of code that prints the data type of the elements in the array.

# PART 2 -
# Printing the data type of the array as a WHOLE
# The output tells us that y is a numpy array

type(y)

numpy.ndarray

In [85]:
# Write a snippet of code that displays `11` from the array.
y[y==11]

array([11])

In [86]:
# Write a snippet of code that multiplies each array element by `7` and displays the new values.
y * 7

array([ 14,  21,  35,  49,  77,  91, 119, 133, 161, 203, 217, 259])