<a href="https://colab.research.google.com/github/qfx4yk/ds1002-qfx4yk/blob/main/in-class%20exercises/06_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Installing & Importing Packages

`numpy` is the first Python package we will be using. External packages not built into Python usually have to be (1) installed and (2) imported.

### Installing

To install any package into your current Google Colab session, use the `!pip` command like this:
```
!pip install numpy
```
However, `numpy` is such a common package it comes pre-installed here.

### Importing
Once a package is installed into your system, it must be imported into any Python code using the `import` command:
```
import numpy
```
### Import Aliases
Python also allows import statements to declare an alias for referencing the package. It is a common practice among `numpy` users to import it as `np` like this:
```
import numpy as np
```

## Basic NumPy Array Functionality

In [ ]:
import numpy as np

# to see all the functionalities within np, type in np. with tab key?

SyntaxError: ignored

In [ ]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# To see how many dimensions are in z
z.shape

(10,)

In [ ]:
z = np.linspace(2, 10, 5)         # go from 2 to 10, with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
a_list = [1,2,3,4,5,6,7]
z = np.array([a_list]) # the NumPy function takes it in as integers
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [ ]:
type(z)

numpy.ndarray

In [ ]:
b_list = [[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]      # 2-dimensional array because it is a list containing two lists; if the lists are different lengths, then you will get an error
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [ ]:
z.shape # format: record, sub-record, number of values in each

(1, 2, 7)

In [ ]:
# Sort an array
# Does not edit the old array; it creates a new array

x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
z = np.array([1, 2, 3, 4, 5])

In [ ]:
# Filter the array
# Gives the output in boolean form

z < 3

array([ True,  True, False, False, False])

In [ ]:
z > 3

array([False, False, False,  True,  True])

In [ ]:
# Apply a mask to an array
# Create a new array with specific values based on what you want

z[z > 3]

array([4, 5])

In [ ]:
# Adding and combining arrays

a_array = np.array([1,2,3,4,5])
b_array = np.array([6,7,8,9,10])

In [ ]:
a_array + b_array

array([ 7,  9, 11, 13, 15])

In [ ]:
a_array + 30

array([31, 32, 33, 34, 35])

In [ ]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

In [ ]:
a_array * 10

array([10, 20, 30, 40, 50])

## Images are Numerical Data

In [ ]:
!pip install scikit-image matplotlib

In [ ]:
import numpy as np
from skimage import io

photo = io.imread('hotel.jpg')
type(photo)

FileNotFoundError: ignored

In [ ]:
photo.shape

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(photo)

In [ ]:
plt.imshow(photo[::-1])

In [ ]:
plt.imshow(photo[:, ::-1])

In [ ]:
plt.imshow(photo[200:400, 300:500])

In [ ]:
plt.imshow(photo[::2, ::2])

In [ ]:
# Get the sin of all three channels of each pixel value

photo_sin = np.sin(photo)
photo_sin

In [ ]:
# Other built-in statistical functions

print(np.sum(photo))
print(np.prod(photo))
print(np.mean(photo))
print(np.std(photo))
print(np.var(photo))
print(np.min(photo))
print(np.max(photo))

In [ ]:
# Search every value in the array, and when a value is above 100, replace it with 255.
# Where it isn't above 100, replace with 0.

photo_masked = np.where(photo > 100, 255, 0)

In [ ]:
plt.imshow(photo_masked)

In [ ]:
# Both filter the values of the array and transpose its axes.
# Switches rows and columns.

plt.imshow(photo[:,:,0].T)